// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrnQFYsmc33oR6gXm3b0G7BUKF0F2GraE',
    appId: '1:893245874517:web:0ea25b6f6e70bbeb760fdc',
    messagingSenderId: '893245874517',
    projectId: 'easymoney-17c05',
    authDomain: 'easymoney-17c05.firebaseapp.com',
    storageBucket: 'easymoney-17c05.appspot.com',
    measurementId: 'G-NR6QG5TNJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxZMZtQv7vzM2XRKmlC-v-nWr1NEEDdIg',
    appId: '1:893245874517:android:284fa6aac7864bcf760fdc',
    messagingSenderId: '893245874517',
    projectId: 'easymoney-17c05',
    storageBucket: 'easymoney-17c05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaOqaH3Ow-gik8t7uAOf8AwxFAiC1oo7k',
    appId: '1:893245874517:ios:0dd8b2916c71e0c5760fdc',
    messagingSenderId: '893245874517',
    projectId: 'easymoney-17c05',
    storageBucket: 'easymoney-17c05.appspot.com',
    androidClientId: '893245874517-maite3rf8j6upc75fjcdb8f2grfku2qi.apps.googleusercontent.com',
    iosClientId: '893245874517-r8qjbm4h6264j44cuq7pvm05ccab9q1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaOqaH3Ow-gik8t7uAOf8AwxFAiC1oo7k',
    appId: '1:893245874517:ios:0b27a2333c2b5276760fdc',
    messagingSenderId: '893245874517',
    projectId: 'easymoney-17c05',
    storageBucket: 'easymoney-17c05.appspot.com',
    androidClientId: '893245874517-maite3rf8j6upc75fjcdb8f2grfku2qi.apps.googleusercontent.com',
    iosClientId: '893245874517-84v6dgkh04kg5r7f9puctrginmkhj0gh.apps.googleusercontent.com',
    iosBundleId: 'com.example.newProject.RunnerTests',
  );
}
